"""Image_name length increase and image_desc type change and changed name of fields

Revision ID: 29dd79cbae77
Revises: 4ded90661d26
Create Date: 2021-11-29 02:12:48.711560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dd79cbae77'
down_revision = '4ded90661d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_content', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('image_content', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('image_content', 'image_name')
    op.drop_column('image_content', 'image_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_content', sa.Column('image_desc', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('image_content', sa.Column('image_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('image_content', 'description')
    op.drop_column('image_content', 'name')
    # ### end Alembic commands ###
