"""Changed image_id to use file_id

Revision ID: 3cc224a1af9c
Revises: d82f34d0a015
Create Date: 2021-12-01 23:57:31.161823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc224a1af9c'
down_revision = 'd82f34d0a015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'image_content', ['file_id'])
    op.add_column('vote_counter', sa.Column('image_file_id', sa.String(length=50), nullable=True))
    op.drop_constraint('vote_counter_image_content_id_fkey', 'vote_counter', type_='foreignkey')
    op.create_foreign_key(None, 'vote_counter', 'image_content', ['image_file_id'], ['file_id'])
    op.drop_column('vote_counter', 'image_content_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_counter', sa.Column('image_content_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vote_counter', type_='foreignkey')
    op.create_foreign_key('vote_counter_image_content_id_fkey', 'vote_counter', 'image_content', ['image_content_id'], ['id'])
    op.drop_column('vote_counter', 'image_file_id')
    op.drop_constraint(None, 'image_content', type_='unique')
    # ### end Alembic commands ###
