"""Removed ImageTags table and moved fields to ImageContent

Revision ID: 4ded90661d26
Revises: 78c89b6695f5
Create Date: 2021-11-28 20:42:33.434625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ded90661d26'
down_revision = '78c89b6695f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_tags')
    op.add_column('image_content', sa.Column('tag_1', sa.String(length=20), nullable=True))
    op.add_column('image_content', sa.Column('tag_2', sa.String(length=20), nullable=True))
    op.add_column('image_content', sa.Column('tag_3', sa.String(length=20), nullable=True))
    op.add_column('image_content', sa.Column('tag_4', sa.String(length=20), nullable=True))
    op.add_column('image_content', sa.Column('tag_5', sa.String(length=20), nullable=True))
    op.add_column('image_content', sa.Column('tag_6', sa.String(length=20), nullable=True))
    op.add_column('image_content', sa.Column('tag_7', sa.String(length=20), nullable=True))
    op.add_column('image_content', sa.Column('tag_8', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_content', 'tag_8')
    op.drop_column('image_content', 'tag_7')
    op.drop_column('image_content', 'tag_6')
    op.drop_column('image_content', 'tag_5')
    op.drop_column('image_content', 'tag_4')
    op.drop_column('image_content', 'tag_3')
    op.drop_column('image_content', 'tag_2')
    op.drop_column('image_content', 'tag_1')
    op.create_table('image_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_1', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tag_2', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tag_3', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tag_4', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tag_5', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tag_6', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tag_7', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tag_8', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_content.id'], name='image_tags_image_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_tags_pkey')
    )
    # ### end Alembic commands ###
