"""Reduced imagecontent title length

Revision ID: 54a90999c26b
Revises: ae2c3ec70cf7
Create Date: 2021-12-09 03:24:13.783552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a90999c26b'
down_revision = 'ae2c3ec70cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_content', sa.Column('title', sa.String(length=20), nullable=False))
    op.drop_column('image_content', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_content', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('image_content', 'title')
    # ### end Alembic commands ###
