"""Changed file_location to file_id and added separate file_location

Revision ID: 652503f9224b
Revises: 29dd79cbae77
Create Date: 2021-11-29 16:08:25.793562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652503f9224b'
down_revision = '29dd79cbae77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_content', sa.Column('file_id', sa.String(length=50), nullable=False))
    op.alter_column('image_content', 'file_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_content', 'file_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('image_content', 'file_id')
    # ### end Alembic commands ###
