"""empty message

Revision ID: 8054d60ec2d2
Revises: 280ec735ed92
Create Date: 2021-11-17 23:50:39.946617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8054d60ec2d2'
down_revision = '280ec735ed92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###
