"""empty message

Revision ID: ae2c3ec70cf7
Revises: 32c8381e5d90
Create Date: 2021-12-02 18:00:34.767548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2c3ec70cf7'
down_revision = '32c8381e5d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name')
    )
    op.add_column('image_tags', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.drop_constraint('image_tags_tag_name_key', 'image_tags', type_='unique')
    op.create_foreign_key(None, 'image_tags', 'tags', ['tag_id'], ['id'])
    op.drop_column('image_tags', 'tag_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_tags', sa.Column('tag_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'image_tags', type_='foreignkey')
    op.create_unique_constraint('image_tags_tag_name_key', 'image_tags', ['tag_name'])
    op.drop_column('image_tags', 'tag_id')
    op.drop_table('tags')
    # ### end Alembic commands ###
