"""VoteCounter model

Revision ID: d82f34d0a015
Revises: 29addbce8981
Create Date: 2021-12-01 16:55:54.737692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82f34d0a015'
down_revision = '29addbce8981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_counter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_content_id', sa.Integer(), nullable=True),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_content_id'], ['image_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_counter')
    op.drop_table('image_tags')
    # ### end Alembic commands ###
